'''
==> WE CAN GENERATE A SEQUENCE OF NUMBERS USING RANGE() FUNCTION .RANGE (10) WILL GENERATE 
NUMBERS FROM 0 TO 9 (10 NUMBERS )

==> WE CAN ALSO DEFINE THE START ,STOP ,STEP SIZE AS RANGE (START ,STOP , STEPSIZE ) STEPSIZE 
DEFAULTS TO 1 IF NOT PROVIDED





'''


a = range(10)

print(a)