age =int(input('Please enter your age '))

# REMEMBER IF YOU ARE USING IF ELSE STATEMENT AND AS YOU KNOW PYTHON IS DIFFERENT THAN OTHER LANGUAGE 
# SO WHEN  YOU USE PYTHON  IN THIS IF ,ELIF OR ELSE SATEMENT FOR THIS WE DONT USE CURLY BRACES SO 
# FOR PRINTING THE MULTIPLE LINE JUST START WRITE PRINT CODE OF ANY ABOVE MENTIONED (IF,ELIF,ELSE)
# AS YOU CAN CHECK I PRINT  THE CODE CHECK CHECK 

if age > 18 :
    print('DEAR SIR/MADAM YOU ARE ELIGIBLE FOR VOTING PLEASE USE YOUR RIGHT AND CHOOSE A BETTER LEADER ')
    print("CHECK CHECK ")


  # THIS LINE OF CODE WILL ALWAYS EXECUTABLE 
print(" HII MR.ABHISHEK ")