'''
PYTHON DOES NOT HAVE UNARY OPERATOR FOR INCREMENT / DECREMENT OPERATOR 
(++/--)
INSTEAD TO INCREMENT A VALUE ,USE A+=1 FOR INCREMENT AND FOR 
DECREMENT OPERATION USE A-=1 
THE ABOVE METTION CODE WILL INCREMENT AND DECREMENT BY 1 RESPECTIVELY .

'''